config/routes.rb
Rails.application.routes.draw do
  resources :imports
  resources :books
  root 'books#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  include Rails.application.routes.url_helpers
  validates :title, presence: true
  
  def qr
    URI::HTTP.build(
      host:'api.qrserver.com',
      path: '/v1/create-qr-code',
      query: {
        data: book_url(self),
        size: "100x100"
      }.to_query
    ).to_s
  end
end

app/models/import.rb
PAGE_SIZE = 100
class Import < ApplicationRecord
  before_create :create_books
  
  private
  
  def create_books
    client = Goodreads::Client.new(
      api_key: ENV.fetch("GOODREADS_KEY"), 
      api_secret: ENV.fetch("GOODREADS_KEY")
    )
    
    (client.shelf(6331420, shelf, per_page: PAGE_SIZE).total / PAGE_SIZE).ceil.times do |page|
      client.shelf(6331420, shelf, per_page: PAGE_SIZE, page: page).books.each do |wrapper|
        Book.create! title: wrapper.book.title, isbn: wrapper.book.isbn
      end
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title)
    end
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  before_action :set_import, only: [:show, :edit, :update, :destroy]

  # GET /imports
  # GET /imports.json
  def index
    @imports = Import.all
  end

  # GET /imports/1
  # GET /imports/1.json
  def show
  end

  # GET /imports/new
  def new
    @import = Import.new
  end

  # GET /imports/1/edit
  def edit
  end

  # POST /imports
  # POST /imports.json
  def create
    @import = Import.new(import_params)

    respond_to do |format|
      if @import.save
        format.html { redirect_to @import, notice: 'Import was successfully created.' }
        format.json { render :show, status: :created, location: @import }
      else
        format.html { render :new }
        format.json { render json: @import.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /imports/1
  # PATCH/PUT /imports/1.json
  def update
    respond_to do |format|
      if @import.update(import_params)
        format.html { redirect_to @import, notice: 'Import was successfully updated.' }
        format.json { render :show, status: :ok, location: @import }
      else
        format.html { render :edit }
        format.json { render json: @import.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imports/1
  # DELETE /imports/1.json
  def destroy
    @import.destroy
    respond_to do |format|
      format.html { redirect_to imports_url, notice: 'Import was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_import
      @import = Import.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def import_params
      params.require(:import).permit(:shelf)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/views/books/_form.html.slim
= form_for @book do |f|
  - if @book.errors.any?
    #error_explanation
      h2 = "#{pluralize(@book.errors.count, "error")} prohibited this book from being saved:"
      ul
        - @book.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .actions = f.submit

app/views/books/edit.html.slim
h1 Editing book

== render 'form'

= link_to 'Show', @book
'  |
= link_to 'Back', books_path

app/views/books/index.html.slim
h1.header Listing books

table
  thead
    tr
      th.header Title
      th
      th
      th
  tbody
    .page
      - @books.each_with_index do |book, index|
        tr.book
          td = book.title
          td
            img.qr src=book.qr

          td.link = link_to 'Show', book
          td.link = link_to 'Edit', edit_book_path(book)
          td.link = link_to 'Destroy', book, data: {confirm: 'Are you sure?'}, method: :delete

br
.link = link_to 'Import Goodreads List', new_import_path
.link = link_to 'New Book', new_book_path

javascript:
  var books = document.getElementsByClassName("book");
  for (var i = 0; i < books.length; i++) {
    if (i % 10 === 8 || i % 10 === 9) {
      books[i].className = books[i].className + " end-of-page"
    }
    if (i % 2 == 0) {
        books[i].className = books[i].className + " left"
    } else {
        books[i].className = books[i].className + " right"
    }
  }


scss:

  @page {
    @page :right {
      @bottom-right {
        content: none;
      }
    }
    size: 8.5in 11in;
  }

  @media print {
    @page {
      margin: 0;
    }
    body {
      margin: 1.6cm;
    }
    .header, .link {
      display: none;
    }
    .book {
      height: 5cm;
    }
  }

  .qr {
    margin-left: 40px;
    margin-right: 40px;
  }

  .book {
    width: 50%;
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: flex-end;
  }

  .end-of-page {
    margin-bottom: 125px;
  }

  .left {
    float: left;
  }

  .right {
    float: right;
  }

app/views/books/new.html.slim
h1 New book

== render 'form'

= link_to 'Back', books_path

app/views/books/show.html.slim
p#notice = notice

p
  strong Title:
  = @book.title

= link_to 'Edit', edit_book_path(@book)
'  |
= link_to 'Back', books_path

app/views/imports/_form.html.slim
= form_for @import do |f|
  - if @import.errors.any?
    #error_explanation
      h2 = "#{pluralize(@import.errors.count, "error")} prohibited this import from being saved:"
      ul
        - @import.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :shelf
    = f.text_field :shelf
  .actions = f.submit

app/views/imports/edit.html.slim
h1 Editing import

== render 'form'

= link_to 'Show', @import
'  |
= link_to 'Back', imports_path

app/views/imports/index.html.slim
h1 Listing imports

table
  thead
    tr
      th Shelf
      th
      th
      th

  tbody
    - @imports.each do |import|
      tr
        td = import.shelf
        td = link_to 'Show', import
        td = link_to 'Edit', edit_import_path(import)
        td = link_to 'Destroy', import, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Import', new_import_path

app/views/imports/new.html.slim
h1 New import

== render 'form'

= link_to 'Back', imports_path

app/views/imports/show.html.slim
p#notice = notice

p
  strong Shelf:
  = @import.shelf

= link_to 'Edit', edit_import_path(@import)
'  |
= link_to 'Back', imports_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExLibris</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>